#!/bin/bash

set -e

cd /etc/swift

rm -f *.builder *.ring.gz backups/*.builder backups/*.ring.gz

swift-ring-builder object.builder create 10 3 1
swift-ring-builder object.builder add r1z1-127.0.0.1:5010/sda1 1
swift-ring-builder object.builder add r1z2-127.0.0.1:5020/sdb1 1
swift-ring-builder object.builder add r1z3-127.0.0.1:5030/sdc1 1
swift-ring-builder object.builder rebalance
swift-ring-builder container.builder create 10 3 1
swift-ring-builder container.builder add r1z1-127.0.0.1:5011/sdd2 1
swift-ring-builder container.builder add r1z2-127.0.0.1:5021/sdd2 1
swift-ring-builder container.builder add r1z3-127.0.0.1:5031/sdd2 1
swift-ring-builder container.builder rebalance
swift-ring-builder account.builder create 10 3 1
swift-ring-builder account.builder add r1z1-127.0.0.1:5012/sdd1 1
swift-ring-builder account.builder add r1z2-127.0.0.1:5022/sdd1 1
swift-ring-builder account.builder add r1z3-127.0.0.1:5032/sdd1 1
swift-ring-builder account.builder rebalance
